output_filename = "generated_module.py"

code = '''def greet(name):
    return f"Hello, {name}! This function was generated by generated_code.py."
'''

with open(output_filename, "w") as f:
    f.write(code)

print(f"Generated {output_filename}")